import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nextjs 13 연습",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <nav
          style={{
            background: "yellow",
            padding: "16px",
            display: "flex",
            justifyContent: "start",
            gap: "16px",
          }}
        >
          <Link
            href={"/"}
            style={{
              fontWeight: "bold",
              fontSize: "16px",
            }}
          >
            Home
          </Link>
          <Link
            href={"/css-practice"}
            style={{
              fontWeight: "bold",
              fontSize: "16px",
            }}
          >
            CSS 연습
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
